version: "3.4"

networks:
  postgres:

volumes:
  postgres-data:
  postgres-log:

services:
  poke-exchange-db:
    image: postgres
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POKE-EXCHANGE-DB-NAME}
      POSTGRES_USER: ${POKE-EXCHANGE-DB-USER}
      POSTGRES_PASSWORD: ${POKE-EXCHANGE-DB-PASSWORD}

  poke-exchange-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
      - ./target:/usr/src/app/target
    networks:
      - postgres
    ports:
      - 8080:8080
    env_file: .env
    environment:
      POSTGRES_DB: ${POKE-EXCHANGE-DB-NAME}
      POSTGRES_URL: ${POKE-EXCHANGE-DB-URL}
      POSTGRES_USER: ${POKE-EXCHANGE-DB-USER}
      POSTGRES_PASSWORD: ${POKE-EXCHANGE-DB-PASSWORD}
      JWT_TOKEN_SECRET: ${JWT-TOKEN-SECRET}