server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://poke-exchange-db:5432/poke_exchange_db
    username: local
    password: local
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs