apiVersion : apps/v1
kind: Deployment
metadata:
  name: "pokexchange-ddaa"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "pokexchange-ddaa"
  template:
    metadata:
      labels:
        app: "pokexchange-ddaa"
    spec:
      containers:
        - name: "pokexchange-ddaa"
          image: "pokexchange.azurecr.io/pokexchange"
          ports:
          - containerPort: 80