apiVersion: v1
kind: Service
metadata:
    name: "pokexchangecluster-34cb"
    labels:
        app: "pokexchangecluster-34cb"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "pokexchangecluster-34cb"