name: Docker build

on:
  release:
    types: [created]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            chukitipok/poke-exchange-api:latest
            chukitipok/poke-exchange-api:${{ steps.tag_name.outputs.TAG_NAME }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy on DEV server
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.WEBHOOK_DEV_SERVER_URL }}
          method: POST
          username: ${{ secrets.DEV_SERVER_USER }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}

